ALTER TABLE employee_qr_codes ADD COLUMN IF NOT EXISTS otp VARCHAR(10);
ALTER TABLE employee_qr_codes ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP;
ALTER TABLE employee_qr_codes ADD COLUMN IF NOT EXISTS is_used BOOLEAN DEFAULT FALSE;
